// This file is generated by Gemini. DO NOT EDIT.
'use server';
/**
 * @fileOverview Analyzes user's exercise form in real-time via webcam and provides corrective feedback.
 *
 * - exerciseFormAnalysisFeedback - A function that handles the exercise form analysis and feedback process.
 * - ExerciseFormAnalysisInput - The input type for the exerciseFormAnalysisFeedback function.
 * - ExerciseFormAnalysisOutput - The return type for the exerciseFormAnalysisFeedback function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ExerciseFormAnalysisInputSchema = z.object({
  videoDataUri: z
    .string()
    .describe(
      "A video of the user performing an exercise, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
  exerciseName: z.string().describe('The name of the exercise being performed.'),
  userDescription: z.string().optional().describe('Optional description of the user performing the exercise, any injuries or limitations'),
});
export type ExerciseFormAnalysisInput = z.infer<typeof ExerciseFormAnalysisInputSchema>;

const ExerciseFormAnalysisOutputSchema = z.object({
  feedback: z.string().describe('Feedback on the user\'s exercise form, including any corrections needed.'),
});
export type ExerciseFormAnalysisOutput = z.infer<typeof ExerciseFormAnalysisOutputSchema>;

export async function exerciseFormAnalysisFeedback(
  input: ExerciseFormAnalysisInput
): Promise<ExerciseFormAnalysisOutput> {
  return exerciseFormAnalysisFeedbackFlow(input);
}

const prompt = ai.definePrompt({
  name: 'exerciseFormAnalysisPrompt',
  input: {schema: ExerciseFormAnalysisInputSchema},
  output: {schema: ExerciseFormAnalysisOutputSchema},
  prompt: `You are a certified personal trainer providing feedback on exercise form. 

You will analyze the exercise form in the video and provide corrective feedback to the user.

Exercise Name: {{{exerciseName}}}
User Description: {{{userDescription}}}
Video: {{media url=videoDataUri}}

Provide specific and actionable feedback to help the user improve their form and reduce the risk of injury.`,
});

const exerciseFormAnalysisFeedbackFlow = ai.defineFlow(
  {
    name: 'exerciseFormAnalysisFeedbackFlow',
    inputSchema: ExerciseFormAnalysisInputSchema,
    outputSchema: ExerciseFormAnalysisOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
